"""
API / Controller layer for CortexSail Agentic RAG system. This module defines the FastAPI application and includes routers for handling API endpoints related to the agent's operations. It serves as the entry point for the API, configuring the app and providing a health check endpoint.
"""
###we use methods defined in the redis_session_manager adn perform actions by passing the required parameters to perform actions on redis related methods

import os

from fastapi import APIRouter, HTTPException, Response, Request, Cookie
from typing import Optional
from pathlib import Path

from fastapi.responses import FileResponse
from src.model.models import ConfluenceUserLoginCredentialsModel, HealthCheckResponseModel, RAGQueryRequest, RAGResponse, DocumentIngestRequest, DocumentIngestResponse, RAGFilters, RequestModelConfluenceAnalyzeDocumentTask, SourceDocument, ConfluenceDocumentFilter, ConfluenceDocumentAnalysisModel,ConfluenceDocumentAnalysisResultModel, WordDocumentGenerationRequestModel
RequestModelConfluenceAnalyzeDocumentTask,
HealthCheckResponseModel,
ConfluenceUserLoginCredentialsModel,

###Write the service layer first before using it with API layer, this is to ensure separation of concerns and maintain a clean architecture. The service layer will handle the business logic and interactions with external systems, while the API layer will focus on handling HTTP requests and responses.
from src.redis.redis_session_manager import ConfluenceSessionManager
from src.services.confluence_service_layer import ConfluenceService
from src.services.vectordb_service import VectorDBService

#Defining the router instance for the API endpoints related to the agent's operations, this will be included in the main FastAPI app in app.py
router = APIRouter()
#Confluence service instance
confluence_service_instance = ConfluenceService()

#API endpoint takes the endpoint path and the response model which is the expected output format of the API response, this helps in automatic validation and documentation generation for the API. 

#For confluence analyze document task
@router.post("/analyze", response_model = ConfluenceDocumentAnalysisModel)
async def analyze_Confluence_document_task(
    request: RequestModelConfluenceAnalyzeDocumentTask,
    # session_id: Optional[str] = Cookie(None)
):
    """API endpoint for analyzing a confluence document based on the provided query.
    
    request: RequestModelConfluenceAnalyzeDocumentTask - The request body containing the query for analyzing the confluence document.

    Args:
    request: JiraAnalysisRequest with the user's prompt for analyzing the confluence document.

    Returns:
    ConfluenceDocumentAnalysisModel: The response model containing the analysis result of the confluence document.
    """
    try:
        if not request.query.strip():
            raise HTTPException(status_code = 400, detail="Query cannot be empty.")


        result = await confluence_service_instance.user_prompt(request.query)

        confluence_analysis_result = ConfluenceDocumentAnalysisResultModel(
            success = result["success"],
            output = result["output"],
            message = result.get("message")
        )

        return ConfluenceDocumentAnalysisModel(response_answer = confluence_analysis_result)
    except Exception as e:
        raise HTTPException(status_code = 500, detail=f"An error occurred while processing the request: {str(e)}")
@router.get("/healthcheck", response_model = HealthCheckResponseModel)
async def healthcheck():
    """
    API endpoint for health check of the service
    """
    result = confluence_service_instance.health_check()

    return HealthCheckResponseModel(
        status = result["status"],
        message = result["message"]
    )

#endpoint for API documentation - root endpoint
@router.get("/")
async def root():
    """
    Root endpoint for the API, provides a welcome message and directs users to the API documentation.
    Returns:
    A JSON response with a welcome message and api documentation
    """
    return{
        "message":"Confluence Agentic RAG API is up and running! Please refer to the /docs endpoint for API documentation and usage details.",
        "description": "This is the root endpoint for the Confluence Agentic RAG API with FastAPI",
        "version": "V1",
        "endpoints": {
            "/analyze": "POST endpoint for analyzing confluence documents based on user queries.",
            "/healthcheck": "GET endpoint for checking the health status of the service.",
            "/docs": "GET endpoint for accessing the interactive API documentation generated by FastAPI."
        }
    }

#Response as the response_model (built-in FastAPI) for setting up - cookie, statuscode, headers for the API response
@router.post("/confluence_login_endpoint",response_model = dict)
async def confluence_login(confluence_credentials: ConfluenceUserLoginCredentialsModel, response: Response):
    result = await confluence_service_instance.confluence_login(confluence_credentials)
    if result.success:
        response.set_cookie(key = "session_id", value = result.session_id)
        return {
            "message": "Confluence login successful"
        }
    else:
        raise HTTPException(status_code = 401, detail = "Confluence login failed, please check your credentials and try again.")
    
#Endpoint to get the session data for the logged in user, this is to verify that the session management is working correctly and the user is able to maintain a session across requests.    
@router.get("/session_data", response_model = dict)
async def get_user_session_data(session_id: str = Cookie(None)):
    """
    Redis session implementation required for this endpoint to work, this is to verify that the session management is working correctly and the user is able to maintain a session across requests.
    """
    ##Instance for the session manager
    session_manager = ConfluenceSessionManager()
    ##Extracting the session data
    redis_session_data = session_manager.get_session_data(session_id)

    if not redis_session_data:
        raise HTTPException(status_code = 404, detail = "Session data not found for the given session_id, please login to create a session and try again.")
    else:
        redis_session_data["confluence_password"] = "********"
    return redis_session_data

##Adding logout route to clear the session data and expire the session in Redis
@router.post("/logout", response_model = dict)
async def confluence_logout(response: Response, session_id: str = Cookie(None)):
    session_manager = ConfluenceSessionManager()
    if session_id:
        session_manager.clear_session(session_id)
    return {
        "message": "Logged out successfully, session cleared."
    }
##Route to generate the word document
##UI(markdown+call this endpt -> request payload(has markdown content)) - > API -> service layer (generate word document from markdown content) -> API (return the generated word document or a link to download the document)
@router.post("/generate-word-document")
async def generate_word_document_definition(request: WordDocumentGenerationRequestModel, session_id: str = Cookie(None)):
    """Generating word document from markdown content"""
    try:
        if not session_id:
            raise HTTPException(status_code = 401, detail = "Invalid session, please login to create a session and try again.")
        result = await confluence_service_instance.produce_word_document_from_markdown(markdown_content=request.generated_content, session_id=session_id)

        if result["success"]:
            return {
                "success": True,
                "filename": result["filename"],
                "message": result["message"]
            }
        else:
            raise HTTPException(status_code = 500, detail = f"Failed to generate word document")
    except Exception as e:
        print(f"Error in /generate-word-document endpoint: {str(e)}")
        raise HTTPException(status_code = 500, detail = f"An error occurred while processing the request: {str(e)}")

@router.get("/download-word-document/{filename}")
async def download_word_document(filename: str, session_id: str = Cookie(None)):
    """
    Endpoint to download the generated word document.
    """
    try:
        if not session_id:
            raise HTTPException(status_code = 401, detail = "Invalid session, please login to create a session and try again.")
        filepath = os.path.join("output",filename)

        if not os.path.exists(filepath):
            raise HTTPException(status_code = 404, detail = "File not found on the server.")
        ##HTTP response but with the actual file, file as response, this is to enable the user to download the file directly when they hit this endpoint with the correct filename, the file will be served as a response with the appropriate headers for downloading the file.
        return FileResponse(
            path = filepath,
            filename = filename,
            media_type = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
        )
    except Exception as e:
        print(f"Error in /download-word-document endpoint: {str(e)}")
        raise HTTPException(status_code = 500, detail = f"An error occurred while processing the request: {str(e)}")

@router.post("/load-vector-database")
async def load_vector_database(csv_path: Optional[str] = None):
    """
    Endpoint to load the vector database with the data from the provided CSV file. 

    Args:
        csv_filepath - Path of CSV file, If not present then we take the latest CSV from input folder

    Returns:
        Success message with the number of loaded records or an error message in case of failure.
    """
    try:
        print("Loading vector database with CSV file data...")

        vector_db = VectorDBService(persistent_directory="./chroma_db")

        if csv_path is None:
            input_dir = Path("./inputs")
            csv_files = list(input_dir.glob("*.csv"))

            if not csv_files:
              raise HTTPException(status_code = 404, detail = "No CSV files found in the input directory.")  
            
            ##Logic for checking the latest modified file in the input directory and using that file for loading the vector database
            #csv_path - stores the path to that file
            csv_path = str(max(csv_files, key = lambda p:p.stat().st_mtime))
            print(f"Using the CSV file {csv_path}")

            if not Path(csv_path).exists():
                raise HTTPException(status_code = 404, detail = f"CSV file not found at the specified path: {csv_path}")
            else:
                loaded_records = vector_db.upload_csv_content(csv_path)

                ##ChromaDB function defined in service layer- get_collection_stats() to get the number of records in the collection after loading the data from the CSV file.

                collection_stats = vector_db.get_collection_details()
                
                ##returning dict for frontend

                return {
                    "success": True,
                    "message": f"Vector database loaded successfully with data from {csv_path}",
                    "loaded_records": loaded_records,
                    "number_of_documents": collection_stats.get("number_of_documents",0),
                    "collection_name": collection_stats.get("collection_name",""),
                    "csv_file": csv_path
                }
    except HTTPException:
        raise
    except Exception as e:
        print(f"Error in /load-vector-database endpoint: {str(e)}")
        raise HTTPException(status_code = 500, detail = f"An error occurred while processing the request: {str(e)}")
    
@router.get("/vector-database-stats")
async def vector_database_stats():
    """
    Endpoint to get the statistics of the vector database collection, this includes the number of documents in the collection and the collection name.
    """
    try:
        vector_db = VectorDBService(persistent_directory="./chroma_db")
        
        collection_stats = vector_db.get_collection_details()

        return {
            "success": True,
            "stats": collection_stats
        }
    except Exception as e:
        raise HTTPException(status_code = 500, detail = f"An error occurred while processing the request: {str(e)}")
@router.delete("/clear-vector-database")
async def clear_vector_database():
    """
    Endpoint to clear the vector database collection, this will delete all the documents in the collection and reset the collection stats.
    """
    try:
        vector_db = VectorDBService(persistent_directory="./chroma_db")
        vector_db.clear_complete_collection()

        return{
            "success": True,
            "message": "Vector database collection cleared successfully."
        }
    except Exception as e:
        raise HTTPException(status_code = 500, detail = f"An error occurred while processing the request: {str(e)}")